### ISSUE TITLE
How to Use

### ISSUE THREAD

**Issue by saidreklaoui** [SkippyZA/ibt-telemetry#1]
Hi!
I can't use you're library. Can you explain step by step how to start? thank you.

**Comment by SkippyZA** [comment]
No idea why I never received a notification for this. Did you ever manage to figure it out? Or did you move on to something else?

**Comment by sblease360** [comment]
I am also trying to use this and getting the following error: 

` App threw an error during load
ReferenceError: regeneratorRuntime is not defined
    at C:\Users\Sam\source\repos\ElectronOverlays\node_modules\ibt-telemetry\lib\telemetry.js:84:12`

I am trying to build this into an electron app with the following code:

`var IbtTelemetry = require('ibt-telemetry')

  IbtTelemetry.fromFile("C:\\Users\\Sam\\Documents\\iRacing\\telemetry\\ferrari488gte_charlotte 2018 oval 2019-12-20 19-30-13.ibt")
    .then(telemtry => {
      console.log(telemetry.toJSON);
    })
`

Any tips, the file path definitely exists - although I may well be referencing it incorrectly.

**Comment by SkippyZA** [comment]
I have never tested this library with windows. If you could supply me with a link to an `ibt` file, I would be happy to take a look at it

**Comment by sblease360** [comment]
Thanks Skippy, its very likely I am doing something wrong, I am far from an expert in JS or Node. The file I was using should be downloadable from here: 

[https://drive.google.com/open?id=1o990uhU32bk7krdVRlRk0-Q8_GGDX-4I](https://drive.google.com/open?id=1o990uhU32bk7krdVRlRk0-Q8_GGDX-4I)

Its only a very small file I was using to prove the concept, its only a few seconds worth and I think the car remains in the pit lane throughout.

Let me know if you need any further info.

**Comment by SkippyZA** [comment]
Ok, so I got it working. The example branch does not work and it took some time digging into it to figure out everything again.

The reason for the `ReferenceError: regeneratorRuntime` error is because I am using an async generator: https://github.com/SkippyZA/ibt-telemetry/blob/master/src/telemetry.js#L61-L79 I was able to resolve this by including `babel-polyfill` as a dependency.

Here is a working piece of code to load up the telemetry file:

```js
require('babel-polyfill')
const { Telemetry } = require('ibt-telemetry')

Telemetry.fromFile('./telemetry.ibt')
  .then(telemetry => {
    console.log(`Unique id: ${telemetry.uniqueId()}`)
  })
```

I hope this gets you started. I may rewrite this library to typescript and remove the need for the async generator, but as I am no longer an iRacing member, I don't have access to any telemetry files to experiment with.

Please feel free to submit a PR to enhance the documentation/example if you would like 👍

**Comment by sblease360** [comment]
Thanks Skippy, I have indeed been able to get this working now.

**Comment by SkippyZA** [comment]
Thanks great stuff. I published a new version which includes some additional constants that have been added.

**Comment by SkippyZA** [comment]
If you could supply me with a race IBT file, I would be interested in updating this library a bit more. I have already done the majority of the conversion to typescript. Will try get a version 2 out soon with doesn’t require Babel plugins and uses callbacks or RxJS streams instead.

**Comment by sblease360** [comment]
Yeah definitely, might not be until after Christmas but I will record one soon and get it uploaded somewhere. Thanks again for your help.

**Comment by sblease360** [comment]
Managed to squeeze a quick race in, selection of ibt files can be found here:

https://drive.google.com/file/d/14-mR4YUCJTKzkqC5G2_mUYrT7CApCv9M/view?usp=sharing

This covers official practice, qualifying and the race itself. Any questions or anything else you need let me know. 

Cheers.
