### ISSUE TITLE
query for timelaps 

### ISSUE THREAD

**Issue by justjapann** [SkippyZA/ibt-telemetry#8]
hi mate, sorry for the noob question, but i noticed that the laptimes are incomplete, how can transform thats values in the times for each completed laps? I read in the pdf that the ibt files are updated every 60 seconds, so I think that's why the laps are incomplete.
https://prnt.sc/cs9hf2puTCds
https://forums.iracing.com/discussion/62/iracing-sdk/p1
https://us.v-cdn.net/6034148/uploads/8DD84H30FIC8/telemetry-11-23-15.pdf

**Comment by SkippyZA** [comment]
You are correct that the YAML is only updated every X seconds.

It's been a while since I worked with the telemetry, but you should be able to calculate the lap times. It would probably be best to ask on the official iRacing forum on how best to do this with the "disk" telemetry. Using live telemetry (which this library doesn't support), it would be possible to calculate it using the values in the lower section around "CarIdxEstTime" etc

**Comment by SkippyZA** [comment]
Just noticed your username, I happen to be visiting Japan until Saturday. Been a wonderful time in this country 🇯🇵

**Comment by justjapann** [comment]
Ahh yes, Japan is a wonderful place for sure, I lived there for most of my life and enjoyed it a lot
